# llamado del diseño a ejecutar
BoxLayoutExample:

# diseño de caja
<BoxLayoutExample>:
    orientation: 'horizontal'
    Button:
        text: 'A'
        size_hint: .5, .5
        # size: '40dp', '40dp'
        # width: '100dp'
        # height: '80dp'

        # x, center_x, right
        # y, center_y, top
        pos_hint: {'center_y': .5}
    
    BoxLayout:
        orientation: 'vertical'   
        spacing: '5dp' 
        Button:
            text: 'B1'
        Button:
            text: 'B2'
        Button:
            text: 'B3'
        Button:
            text: 'B4'

    Label:
        text: 'C'

# diseño principal
<MainWidget>:
    Button:
        text: 'Prueba'
        size: '100dp', '80dp'
        pos: '200dp', '200dp'
    Button:
        text: 'Prueba2'
        size: '100dp', '80dp' # fija un tamaño al boton
        pos: '100dp', '200dp'
        color: 0, 0, 1, 1
    Label:
        text: 'Prueba2'
        size: '100dp', '80dp'
        pos: '150dp', '250dp'
        color: 1, 0, 0, 1

