# llamado del diseño a ejecutar
mylayout:

<mylayout>:
    # diseño de caja
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height # ancho y alto definido por la ventana
        
        # entrada de texto
        TextInput:
            id: calc_input
            text: '0'
            halign: 'right' # alineacion del texto a la derecha 
            font_size: 62 # tamaño de la fuente
            size_hint: (1, .15)

        # diseño de cuadricula
        GridLayout:
            cols: 4
            rows: 5
            spacing: '1dp'

            # botones de primera fila
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '%'
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: 'CE'
            Button:
                id: clear
                size_hint: (.2, .2)
                font_size: 30
                text: 'C'
                on_press: root.clear()
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '/'

            # botones de segunda fila
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '7'
                background_color: (157/255, 157/255, 157/255, 1)
                on_press: root.button_press(7)
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '8'
                background_color: (157/255, 157/255, 157/255, 1)
                on_press: root.button_press(8)
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '9'
                background_color: (157/255, 157/255, 157/255, 1)
                on_press: root.button_press(9)
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: 'X'

            # botones de tercera fila
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '4'
                background_color: (157/255, 157/255, 157/255, 1)
                on_press: root.button_press(4)
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '5'
                background_color: (157/255, 157/255, 157/255, 1)
                on_press: root.button_press(5)
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '6'
                background_color: (157/255, 157/255, 157/255, 1)
                on_press: root.button_press(6)
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '-'

            # botones de cuarta fila
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '1'
                background_color: (157/255, 157/255, 157/255, 1)
                on_press: root.button_press(1)
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '2'
                background_color: (157/255, 157/255, 157/255, 1)
                on_press: root.button_press(2)
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '3'
                background_color: (157/255, 157/255, 157/255, 1)
                on_press: root.button_press(3)
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '+'

            # botones de quinta fila
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '+/-'
                background_color: (157/255, 157/255, 157/255, 1)
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '0'
                background_color: (157/255, 157/255, 157/255, 1)
                on_press: root.button_press(0)
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '.'
                background_color: (157/255, 157/255, 157/255, 1)
            Button:
                size_hint: (.2, .2)
                font_size: 30
                text: '='
                background_color: (249/255, 240/255, 31/255, 1)